const NCKH_TYPE_OPTIONS = [
  {
    value: "de-tai-du-an",
    label: "Đề tài, dự án",
    loaiNckh: "DETAI_DUAN",
    implemented: true,
    mode: "standard",
    mainActorLabel: "Chủ nhiệm",
    hasSecondaryMembers: true,
    phanLoaiPlaceholder: "-- Chọn cấp đề tài --",
    showSoNamThucHien: true,
    showMaSo: true,
    showKetQua: false,
    showNgayNghiemThu: false,
    showNgayQuyetDinh: false,
  },
  {
    value: "bai-bao-khoa-hoc",
    label: "Bài báo khoa học",
    loaiNckh: "BAIBAO",
    implemented: true,
    mode: "standard",
    mainActorLabel: "Tác giả chính",
    hasSecondaryMembers: true,
    phanLoaiPlaceholder: "-- Chọn loại tạp chí --",
    showSoNamThucHien: true,
    showMaSo: true,
    maSoLabel: "Chỉ số tạp chí/Mã số",
    showKetQua: false,
    showNgayNghiemThu: true,
    showNgayQuyetDinh: false,
  },
  {
    value: "sang-kien",
    label: "Sáng kiến",
    loaiNckh: "SANGKIEN",
    implemented: true,
    mode: "standard",
    mainActorLabel: "Tác giả",
    hasSecondaryMembers: true,
    phanLoaiPlaceholder: "-- Chọn loại sáng kiến --",
    showSoNamThucHien: true,
    showMaSo: false,
    showKetQua: true,
    showNgayNghiemThu: true,
    showNgayQuyetDinh: false,
  },
  {
    value: "giai-thuong",
    label: "Giải thưởng và sáng chế",
    loaiNckh: "GIAITHUONG",
    implemented: true,
    mode: "standard",
    mainActorLabel: "Tác giả",
    hasSecondaryMembers: true,
    phanLoaiPlaceholder: "-- Chọn loại giải thưởng/sáng chế --",
    showSoNamThucHien: true,
    showMaSo: true,
    maSoLabel: "Mã số",
    showKetQua: true,
    showNgayNghiemThu: true,
    showNgayQuyetDinh: true,
  },
  {
    value: "de-xuat-nghien-cuu",
    label: "Đề xuất nghiên cứu",
    loaiNckh: "DEXUAT",
    implemented: true,
    mode: "equal",
    mainActorLabel: "Người đề xuất chính",
    hasSecondaryMembers: true,
    phanLoaiPlaceholder: "-- Chọn cấp đề xuất --",
    showSoNamThucHien: false,
    showMaSo: false,
    showKetQua: true,
    showNgayNghiemThu: true,
    showNgayQuyetDinh: false,
  },
  {
    value: "sach-giao-trinh",
    label: "Sách, giáo trình",
    loaiNckh: "SACHGIAOTRINH",
    implemented: true,
    mode: "standard",
    mainActorLabel: "Tác giả/Chủ biên",
    hasSecondaryMembers: true,
    secondaryMemberLabel: "Đồng chủ biên/Thành viên",
    phanLoaiPlaceholder: "-- Chọn loại sách/giáo trình --",
    showSoNamThucHien: true,
    showMaSo: true,
    maSoLabel: "Số xuất bản/Mã số",
    showKetQua: true,
    showNgayNghiemThu: true,
    showNgayQuyetDinh: false,
  },
  {
    value: "huong-dan-sv-nckh",
    label: "Hướng dẫn SV NCKH",
    loaiNckh: "HUONGDAN",
    implemented: true,
    mode: "equal",
    mainActorLabel: "Cán bộ hướng dẫn tham gia",
    hasSecondaryMembers: false,
    phanLoaiPlaceholder: "-- Chọn loại hướng dẫn --",
    showSoNamThucHien: false,
    showMaSo: true,
    showKetQua: true,
    showNgayNghiemThu: true,
    showNgayQuyetDinh: false,
  },
  {
    value: "thanh-vien-hoi-dong",
    label: "Thành viên hội đồng khoa học",
    loaiNckh: "HOIDONG",
    implemented: true,
    mode: "fixed",
    mainActorLabel: "Thành viên hội đồng",
    hasSecondaryMembers: false,
    phanLoaiPlaceholder: "-- Chọn loại hội đồng --",
    showSoNamThucHien: false,
    showMaSo: true,
    maSoLabel: "Số quyết định",
    showKetQua: false,
    showNgayNghiemThu: false,
    showNgayQuyetDinh: false,
  },
];

const DEFAULT_NCKH_TYPE = "de-tai-du-an";

const TYPE_ALIASES = {
  "giai-thuong-sang-che": "giai-thuong",
  "hoi-dong-khoa-hoc": "thanh-vien-hoi-dong",
};

const getTypeByValue = (value) =>
  NCKH_TYPE_OPTIONS.find((item) => item.value === value) || null;

const resolveSelectedType = (requestedType) => {
  const normalized = TYPE_ALIASES[requestedType] || requestedType;
  return getTypeByValue(normalized) ? normalized : DEFAULT_NCKH_TYPE;
};

module.exports = {
  NCKH_TYPE_OPTIONS,
  DEFAULT_NCKH_TYPE,
  TYPE_ALIASES,
  getTypeByValue,
  resolveSelectedType,
};
